# Generated by Django 3.2 on 2021-05-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_auto_20210509_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': 'id', 'ordering': ['id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'get_latest_by': 'id', 'ordering': ['id'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'id', 'ordering': ['id'], 'verbose_name': '话题', 'verbose_name_plural': '话题'},
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='topic',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
