# Generated by Django 3.2 on 2021-06-06 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weblog', '0006_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='oauth.user', verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
