# Generated by Django 3.2.4 on 2021-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_topic_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collect_count',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏量'),
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='喜欢数'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='category',
            name='follow_count',
            field=models.PositiveIntegerField(default=0, verbose_name='关注量'),
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='喜欢数'),
        ),
        migrations.AddField(
            model_name='topic',
            name='follow_count',
            field=models.PositiveIntegerField(default=0, verbose_name='关注量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
