# Generated by Django 3.2 on 2021-07-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_auto_20210702_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='collect_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='follow_count',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='follow_count',
        ),
        migrations.AlterField(
            model_name='article',
            name='body_html',
            field=models.TextField(editable=False, verbose_name='源码'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, editable=False, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='body_html',
            field=models.TextField(editable=False, verbose_name='源码'),
        ),
    ]
