# Generated by Django 3.2 on 2021-06-05 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('follows', '0002_auto_20210523_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='对象主键'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('content_type', 'object_id', 'sender')},
        ),
        migrations.AlterIndexTogether(
            name='follow',
            index_together={('content_type', 'object_id')},
        ),
    ]
