# Generated by Django 3.2 on 2021-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210528_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_num',
        ),
        migrations.AddField(
            model_name='question',
            name='max_choices',
            field=models.IntegerField(default=1, verbose_name='最多几项'),
            preserve_default=False,
        ),
    ]
