# Generated by Django 3.2 on 2021-05-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210529_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_choices',
            field=models.PositiveSmallIntegerField(verbose_name='最多几项'),
        ),
    ]
