# Generated by Django 3.2 on 2021-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_max_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_choices',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='最多几项'),
        ),
    ]
