# Generated by Django 3.2.4 on 2021-10-09 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_max_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='截止时间'),
            preserve_default=False,
        ),
    ]
