# Generated by Django 3.2 on 2021-05-23 06:25

from django.db import migrations, models
import oauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'user_id', 'ordering': ['user_id'], 'verbose_name': '个人资料', 'verbose_name_plural': '个人资料'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'id', 'ordering': ['id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(None, '保密'), (0, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nick_mtime',
            field=models.DateTimeField(default=oauth.models._nickname_mtime, editable=False, verbose_name='改名时间'),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.IntegerField(choices=[(1, '省'), (2, '市'), (3, '县'), (4, '镇'), (5, '村')], verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_mtime',
            field=models.DateTimeField(default=oauth.models._username_mtime, editable=False, verbose_name='改名时间'),
        ),
    ]
