# Generated by Django 3.2 on 2021-05-24 14:00

from django.db import migrations
import oauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20210523_1425'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', oauth.models.UserManager()),
            ],
        ),
    ]
