# Generated by Django 3.2 on 2021-05-29 16:07

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='BaiJiaXing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('dynasty', models.CharField(max_length=64, verbose_name='朝代')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '百家姓',
                'verbose_name_plural': '百家姓',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='CaoCao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '曹操',
                'verbose_name_plural': '曹操',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='ChuLyric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('section', models.CharField(max_length=64, verbose_name='章节')),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '楚辞',
                'verbose_name_plural': '楚辞',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='DiZiGui',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('chapter', models.CharField(max_length=64, verbose_name='篇章')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '弟子规',
                'verbose_name_plural': '弟子规',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='GuWenGuanZhi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('source', models.CharField(max_length=64, verbose_name='来源')),
                ('chapter', models.CharField(max_length=64, verbose_name='篇章')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '古文观止',
                'verbose_name_plural': '古文观止',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='HuaJianji',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('rhythm', models.CharField(max_length=64, verbose_name='韵律')),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '花间集',
                'verbose_name_plural': '花间集',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='LunYu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '论语',
                'verbose_name_plural': '论语',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='NanTang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('rhythm', models.CharField(max_length=64, verbose_name='韵律')),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '南唐',
                'verbose_name_plural': '南唐',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='QianJiaShi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('tape', models.CharField(max_length=64, verbose_name='类型')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '千家诗',
                'verbose_name_plural': '千家诗',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='QianZiWen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('dynasty', models.CharField(max_length=64, verbose_name='朝代')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '千字文',
                'verbose_name_plural': '千字文',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='SanZiJing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('tape', models.CharField(max_length=64, verbose_name='类型')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '三字经',
                'verbose_name_plural': '三字经',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Shijing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('chapter', models.CharField(max_length=64, verbose_name='篇章')),
                ('section', models.CharField(max_length=64, verbose_name='章节')),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '诗经',
                'verbose_name_plural': '诗经',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='ShiSanBai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('tape', models.CharField(max_length=64, verbose_name='类型')),
                ('chapter', models.CharField(max_length=64, verbose_name='篇章')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '唐诗三百首',
                'verbose_name_plural': '唐诗三百首',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='SiShuWuJing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '四书五经',
                'verbose_name_plural': '四书五经',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='SongLyric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('rhythm', models.CharField(max_length=64, verbose_name='韵律')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '宋词',
                'verbose_name_plural': '宋词',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='SongPoem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '宋诗',
                'verbose_name_plural': '宋诗',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '诗词平仄',
                'verbose_name_plural': '诗词平仄',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='TangPoem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'verbose_name': '唐诗',
                'verbose_name_plural': '唐诗',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='XingOrigin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('dynasty', models.CharField(max_length=64, verbose_name='朝代')),
                ('surname', models.CharField(max_length=64, verbose_name='姓氏')),
                ('place', models.CharField(max_length=64, verbose_name='位置')),
            ],
            options={
                'verbose_name': '百家姓起源',
                'verbose_name_plural': '百家姓起源',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='YuanQu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('dynasty', models.CharField(max_length=64, verbose_name='朝代')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '元曲',
                'verbose_name_plural': '元曲',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='ZhiZiJiaXun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
            options={
                'verbose_name': '朱子家训',
                'verbose_name_plural': '朱子家训',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
    ]
