# Generated by Django 3.2 on 2021-06-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_author_dynasty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songlyric',
            name='title',
        ),
    ]
