# Generated by Django 3.2.4 on 2021-10-09 07:15

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0003_remove_songlyric_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouMengYing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('comment', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
            ],
            options={
                'verbose_name': '幽梦影',
                'verbose_name_plural': '幽梦影',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.RenameModel(
            old_name='ZhiZiJiaXun',
            new_name='ZhuZiJiaXun',
        ),
    ]
